-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mm_mm_Pipeline_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_AB_port_AWVALID : OUT STD_LOGIC;
    m_axi_AB_port_AWREADY : IN STD_LOGIC;
    m_axi_AB_port_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AB_port_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AB_port_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AB_port_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AB_port_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AB_port_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AB_port_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AB_port_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AB_port_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AB_port_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_WVALID : OUT STD_LOGIC;
    m_axi_AB_port_WREADY : IN STD_LOGIC;
    m_axi_AB_port_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AB_port_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AB_port_WLAST : OUT STD_LOGIC;
    m_axi_AB_port_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_ARVALID : OUT STD_LOGIC;
    m_axi_AB_port_ARREADY : IN STD_LOGIC;
    m_axi_AB_port_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AB_port_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AB_port_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AB_port_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AB_port_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AB_port_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AB_port_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AB_port_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AB_port_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AB_port_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_RVALID : IN STD_LOGIC;
    m_axi_AB_port_RREADY : OUT STD_LOGIC;
    m_axi_AB_port_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AB_port_RLAST : IN STD_LOGIC;
    m_axi_AB_port_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_AB_port_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AB_port_BVALID : IN STD_LOGIC;
    m_axi_AB_port_BREADY : OUT STD_LOGIC;
    m_axi_AB_port_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AB_port_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AB_port_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln53 : IN STD_LOGIC_VECTOR (61 downto 0);
    AB_buff_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_ce0 : OUT STD_LOGIC;
    AB_buff_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_buff_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_1_ce0 : OUT STD_LOGIC;
    AB_buff_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_buff_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_2_ce0 : OUT STD_LOGIC;
    AB_buff_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_buff_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_3_ce0 : OUT STD_LOGIC;
    AB_buff_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_buff_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_4_ce0 : OUT STD_LOGIC;
    AB_buff_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_buff_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_5_ce0 : OUT STD_LOGIC;
    AB_buff_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_buff_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_6_ce0 : OUT STD_LOGIC;
    AB_buff_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_buff_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    AB_buff_7_ce0 : OUT STD_LOGIC;
    AB_buff_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of mm_mm_Pipeline_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exitcond5_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal AB_port_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond5_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_22_fu_240_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_22_reg_331 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_254_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_341 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal p_cast53_fu_228_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal loop_index_fu_72 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_21_fu_212_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_loop_index_load : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_fu_218_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mm_mux_83_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mm_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_83_32_1_1_U222 : component mm_mux_83_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => AB_buff_q0,
        din1 => AB_buff_1_q0,
        din2 => AB_buff_2_q0,
        din3 => AB_buff_3_q0,
        din4 => AB_buff_4_q0,
        din5 => AB_buff_5_q0,
        din6 => AB_buff_6_q0,
        din7 => AB_buff_7_q0,
        din8 => empty_22_reg_331,
        dout => tmp_fu_254_p10);

    flow_control_loop_pipe_sequential_init_U : component mm_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    loop_index_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((exitcond5_fu_206_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    loop_index_fu_72 <= empty_21_fu_212_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    loop_index_fu_72 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                exitcond5_reg_287 <= exitcond5_fu_206_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond5_fu_206_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_22_reg_331 <= empty_22_fu_240_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond5_reg_287 = ap_const_lv1_0))) then
                tmp_reg_341 <= tmp_fu_254_p10;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    AB_buff_1_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_1_ce0 <= ap_const_logic_1;
        else 
            AB_buff_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    AB_buff_2_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_2_ce0 <= ap_const_logic_1;
        else 
            AB_buff_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    AB_buff_3_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_3_ce0 <= ap_const_logic_1;
        else 
            AB_buff_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    AB_buff_4_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_4_ce0 <= ap_const_logic_1;
        else 
            AB_buff_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    AB_buff_5_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_5_ce0 <= ap_const_logic_1;
        else 
            AB_buff_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    AB_buff_6_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_6_ce0 <= ap_const_logic_1;
        else 
            AB_buff_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    AB_buff_7_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_7_ce0 <= ap_const_logic_1;
        else 
            AB_buff_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    AB_buff_address0 <= p_cast53_fu_228_p1(3 - 1 downto 0);

    AB_buff_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            AB_buff_ce0 <= ap_const_logic_1;
        else 
            AB_buff_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    AB_port_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_AB_port_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            AB_port_blk_n_W <= m_axi_AB_port_WREADY;
        else 
            AB_port_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_AB_port_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_AB_port_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_AB_port_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_AB_port_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, exitcond5_fu_206_p2)
    begin
        if (((exitcond5_fu_206_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, exitcond5_reg_287)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond5_reg_287 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_loop_index_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, loop_index_fu_72, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_loop_index_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_loop_index_load <= loop_index_fu_72;
        end if; 
    end process;

    empty_21_fu_212_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_loop_index_load) + unsigned(ap_const_lv7_1));
    empty_22_fu_240_p1 <= ap_sig_allocacmp_loop_index_load(3 - 1 downto 0);
    exitcond5_fu_206_p2 <= "1" when (ap_sig_allocacmp_loop_index_load = ap_const_lv7_40) else "0";
    m_axi_AB_port_ARADDR <= ap_const_lv64_0;
    m_axi_AB_port_ARBURST <= ap_const_lv2_0;
    m_axi_AB_port_ARCACHE <= ap_const_lv4_0;
    m_axi_AB_port_ARID <= ap_const_lv1_0;
    m_axi_AB_port_ARLEN <= ap_const_lv32_0;
    m_axi_AB_port_ARLOCK <= ap_const_lv2_0;
    m_axi_AB_port_ARPROT <= ap_const_lv3_0;
    m_axi_AB_port_ARQOS <= ap_const_lv4_0;
    m_axi_AB_port_ARREGION <= ap_const_lv4_0;
    m_axi_AB_port_ARSIZE <= ap_const_lv3_0;
    m_axi_AB_port_ARUSER <= ap_const_lv1_0;
    m_axi_AB_port_ARVALID <= ap_const_logic_0;
    m_axi_AB_port_AWADDR <= ap_const_lv64_0;
    m_axi_AB_port_AWBURST <= ap_const_lv2_0;
    m_axi_AB_port_AWCACHE <= ap_const_lv4_0;
    m_axi_AB_port_AWID <= ap_const_lv1_0;
    m_axi_AB_port_AWLEN <= ap_const_lv32_0;
    m_axi_AB_port_AWLOCK <= ap_const_lv2_0;
    m_axi_AB_port_AWPROT <= ap_const_lv3_0;
    m_axi_AB_port_AWQOS <= ap_const_lv4_0;
    m_axi_AB_port_AWREGION <= ap_const_lv4_0;
    m_axi_AB_port_AWSIZE <= ap_const_lv3_0;
    m_axi_AB_port_AWUSER <= ap_const_lv1_0;
    m_axi_AB_port_AWVALID <= ap_const_logic_0;
    m_axi_AB_port_BREADY <= ap_const_logic_0;
    m_axi_AB_port_RREADY <= ap_const_logic_0;
    m_axi_AB_port_WDATA <= tmp_reg_341;
    m_axi_AB_port_WID <= ap_const_lv1_0;
    m_axi_AB_port_WLAST <= ap_const_logic_0;
    m_axi_AB_port_WSTRB <= ap_const_lv4_F;
    m_axi_AB_port_WUSER <= ap_const_lv1_0;

    m_axi_AB_port_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_AB_port_WVALID <= ap_const_logic_1;
        else 
            m_axi_AB_port_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_cast53_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_218_p4),64));
    tmp_2_fu_218_p4 <= ap_sig_allocacmp_loop_index_load(5 downto 3);
end behav;
